<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="s1" duration-ms="23380" started-at="2018-11-26T10:08:00Z" finished-at="2018-11-26T10:08:23Z">
    <groups>
    </groups>
    <test name="test1" duration-ms="23380" started-at="2018-11-26T10:08:00Z" finished-at="2018-11-26T10:08:23Z">
      <class name="com.webtest.demo.Front_Login_Test">
        <test-method status="PASS" signature="doBeforeSuite()[pri:0, instance:com.webtest.demo.Front_Login_Test@37d31475]" name="doBeforeSuite" is-config="true" duration-ms="10169" started-at="2018-11-26T10:07:50Z" finished-at="2018-11-26T10:08:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeSuite -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.webtest.demo.Front_Login_Test@37d31475]" name="setup" is-config="true" duration-ms="0" started-at="2018-11-26T10:08:00Z" finished-at="2018-11-26T10:08:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="LoginFailed()[pri:0, instance:com.webtest.demo.Front_Login_Test@37d31475]" name="LoginFailed" duration-ms="12189" started-at="2018-11-26T10:08:00Z" finished-at="2018-11-26T10:08:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.webtest.demo.Front_Login_Test.LoginFailed(Front_Login_Test.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailed -->
        <test-method status="PASS" signature="LoginSuccess()[pri:0, instance:com.webtest.demo.Front_Login_Test@37d31475]" name="LoginSuccess" duration-ms="11144" started-at="2018-11-26T10:08:12Z" finished-at="2018-11-26T10:08:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccess -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.webtest.demo.Front_Login_Test@37d31475]" name="setup" is-config="true" duration-ms="0" started-at="2018-11-26T10:08:12Z" finished-at="2018-11-26T10:08:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
      </class> <!-- com.webtest.demo.Front_Login_Test -->
    </test> <!-- test1 -->
  </suite> <!-- s1 -->
</testng-results>
